### ISSUE TITLE
Of rendering & more

### ISSUE THREAD

**Issue by romgrk** [rhysd/neovim-component#1] opened 2015-12-05 06:18 UTC
Hello,

I was just curious and had some a question about this project, because I was in the process of looking to write something like this. I saw you have planned rendering this with WebGL, any precise schedule? (No pressure at all intended, just for my information; this all looks like great work).

**Comment by rhysd** [comment] 2015-12-06 14:06
Hi,

I don't have any precise plan to implement the item yet because

- I've not completed to implement all processes for UI events sent from neovim process yet
- I must take profiling before adopting WebGL (pixi.js) at first to avoid premature optimization.

**Comment by rhysd** [comment] 2015-12-10 17:06
I'll close this because I took profile and concluded that rendering with WebGL does not have so much priority in #2.
If you notice some mistakes (e.g. the way of profiling was wrong), it's very helpful to pointing it out.

**Closed by rhysd** 2015-12-10 17:06 UTC

**Comment by romgrk** [comment] 2015-12-12 01:14
Hello, the initial trigger for my question was the fact that, in the example, the rendering of the component was broken (on my side). 
Taking in count that you've done profiling, I am guessing that it is rendering correctly on your side.
By broken rendering I mean: screen not updating in full, i.e. when scrolling 1 line, not all screen-lines are re-rendered. (steps: git pull && rake)
Question 2: Am I doing something wrong, doctor?
(Otherwise I'll fill a proper report if you need)

**Comment by rhysd** [comment] 2015-12-12 17:32
@romgrk 

Ah, if you can, please report the bug by creating an issue with how to reproduce.  Screenshot or animation/screencast is also very helpful.

> Question 2: Am I doing something wrong, doctor?

You can see the log with Chrome DevTools.
There is three log levels; production, debug, not-specified.

Please try `rake debug` and check the console in DevTools.  All logs are dumped to it.
